name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Set to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest # Adjust according to your test framework

      - name: Start FastAPI server
        run: uvicorn app.main:app --host 127.0.0.1 --port ${{ env.PORT }} # Adjust `app.main:app` based on your application's structure
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Deploy
        run: ./deploy_script.sh # Replace with your deployment script or command
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}